### ISSUE TITLE
Stuck on loading in Onlyoffice Desktop Editor

### ISSUE THREAD

**Issue by Kaito-Kiddo** [ONLYOFFICE/plugin-telegram#4]
Whenever i click on Telegram Plugin its doesnt load 
and sometimes crashed Onlyoffice Desktop
I cant sign in 
so i cant get to step 2 of How to use
<img width="316" alt="onlyoffice telegram plugin error" src="https://user-images.githubusercontent.com/48343906/149887955-8f5adabb-cd7d-4c65-83b8-6a85b0a10e5f.png">

Kindly tell whr to get latest version i am using this plugin
[telegram.zip](https://github.com/ONLYOFFICE/plugin-telegram/files/7886914/telegram.zip)

**Comment by ShockwaveNN** [comment]
You're defenetly using not the latest version because your plugin structure looks like this:
![image](https://user-images.githubusercontent.com/668524/149890563-9f05e2fa-6c9e-4610-9fdd-77952b4dfad7.png)
And current stable version has some folders
![image](https://user-images.githubusercontent.com/668524/149890605-c6bd4366-69eb-4640-85de-dae1d8b23417.png)

You should download latest plugin from git and use [this instruction](https://api.onlyoffice.com/plugin/installation/desktop) to install

**Comment by Kaito-Kiddo** [comment]
<img width="685" alt="samescreen on add telegram plugin" src="https://user-images.githubusercontent.com/48343906/157800272-30b88bb2-ca7b-4dae-9356-32348f627dd0.png">
I tried with latest version also but am unable to add the plugin whenever i click add and choose the zip file which i renamed to plugin nothing happens same screen just a blink of screen!

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
